# Generated by Django 6.0.5 on 2026-05-22 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportacaoArquivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo_nome", models.CharField(max_length=255)),
                ("importado_em", models.DateTimeField(auto_now_add=True)),
                ("total_operacoes", models.IntegerField(default=0)),
                ("observacao", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Importação de Arquivo",
                "verbose_name_plural": "Importações de Arquivos",
                "ordering": ["-importado_em"],
            },
        ),
        migrations.CreateModel(
            name="SessaoOperacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_sessao", models.DateField()),
                (
                    "resultado_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_operacoes", models.IntegerField(default=0)),
                ("total_wins", models.IntegerField(default=0)),
                ("total_losses", models.IntegerField(default=0)),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes",
                        to="trades.importacaoarquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Operação",
                "verbose_name_plural": "Sessões de Operações",
                "ordering": ["-data_sessao"],
                "unique_together": {("importacao", "data_sessao")},
            },
        ),
        migrations.CreateModel(
            name="Operacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.CharField(max_length=20)),
                (
                    "lado",
                    models.CharField(
                        choices=[("C", "Comprado"), ("V", "Vendido")], max_length=1
                    ),
                ),
                ("houve_preco_medio", models.BooleanField(default=False)),
                ("abertura", models.DateTimeField()),
                ("fechamento", models.DateTimeField()),
                ("tempo_operacao", models.CharField(max_length=20)),
                (
                    "tempo_entre_trades",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("qtd_compra", models.IntegerField()),
                ("qtd_venda", models.IntegerField()),
                ("preco_compra", models.DecimalField(decimal_places=2, max_digits=12)),
                ("preco_venda", models.DecimalField(decimal_places=2, max_digits=12)),
                ("preco_mercado", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "preco_medio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "mep",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "men",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "resultado_intervalo_pontos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "resultado_intervalo_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "resultado_operacao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "resultado_operacao_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "ganho_maximo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "perda_maxima",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_acumulado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operacoes",
                        to="trades.importacaoarquivo",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operacoes",
                        to="trades.sessaooperacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operação",
                "verbose_name_plural": "Operações",
                "ordering": ["abertura"],
            },
        ),
    ]
