# Generated by Django 6.0.5 on 2026-06-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametrosTrader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempo_minimo_entre_trades",
                    models.IntegerField(
                        default=2,
                        help_text="Operação aberta em menos deste tempo após um loss é marcada como suspeita de revenge trading.",
                        verbose_name="Tempo mínimo entre trades (min)",
                    ),
                ),
                (
                    "max_operacoes_dia",
                    models.IntegerField(
                        default=5,
                        help_text="Dias com mais operações que este valor são sinalizados como possível overtrading.",
                        verbose_name="Máximo de operações por dia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parâmetros do Trader",
                "verbose_name_plural": "Parâmetros do Trader",
            },
        ),
    ]
