# Generated by Django 6.0.5 on 2026-06-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0002_parametrostrader"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalOperacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setup", models.CharField(blank=True, max_length=50)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags separadas por vírgula",
                        max_length=200,
                    ),
                ),
                (
                    "emocao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calmo", "Calmo"),
                            ("ansioso", "Ansioso"),
                            ("confiante", "Confiante"),
                            ("frustrado", "Frustrado"),
                            ("neutro", "Neutro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("qualidade_entrada", models.IntegerField(blank=True, null=True)),
                ("qualidade_saida", models.IntegerField(blank=True, null=True)),
                ("anotacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "operacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal",
                        to="trades.operacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de Operação",
                "verbose_name_plural": "Journal de Operações",
                "ordering": ["-operacao__abertura"],
            },
        ),
    ]
