# Generated by Django 6.0.5 on 2026-06-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0003_journaloperacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrostrader",
            name="capital_inicial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
