# Generated by Django 6.0.5 on 2026-06-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0004_parametrostrader_capital_inicial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operacao",
            old_name="resultado_intervalo_pontos",
            new_name="resultado_operacao_pontos",
        ),
        migrations.RemoveField(
            model_name="operacao",
            name="resultado_intervalo_pct",
        ),
        migrations.RemoveField(
            model_name="operacao",
            name="resultado_operacao_pct",
        ),
    ]
