# Generated by Django 6.0.5 on 2026-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trades",
            "0005_rename_resultado_intervalo_pontos_operacao_resultado_operacao_pontos_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AnotacaoDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_sessao", models.DateField(unique=True)),
                ("contexto_mercado", models.TextField(blank=True)),
                (
                    "estado_emocional",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calmo", "Calmo"),
                            ("ansioso", "Ansioso"),
                            ("confiante", "Confiante"),
                            ("frustrado", "Frustrado"),
                            ("neutro", "Neutro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score_dia", models.IntegerField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anotação do Dia",
                "verbose_name_plural": "Anotações do Dia",
                "ordering": ["-data_sessao"],
            },
        ),
    ]
