# Generated by Django 6.0.5 on 2026-06-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0006_anotacaodia"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrostrader",
            name="drawdown_maximo_permitido",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Alerta disparado quando o drawdown do período superar este valor. 0 = sem limite.",
                max_digits=10,
                verbose_name="Drawdown máximo permitido (R$)",
            ),
        ),
        migrations.AddField(
            model_name="parametrostrader",
            name="meta_resultado_mensal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Meta de resultado financeiro para o mês corrente. 0 = sem meta.",
                max_digits=10,
                verbose_name="Meta de resultado mensal (R$)",
            ),
        ),
    ]
